# vim: set ft=yaml
---

# System
dev_user: vagrant
limits:
  nofile: 8192
  nproc: 10024


# IDEA
idea_url: https://download-cf.jetbrains.com/idea/ideaIC-2016.2.4.tar.gz 
idea_sha256: bfd1bc75386d22bf9f0559b4894b547689383bd69c4038a1516a6e2c00f96742

# HDFS
dfs_permissions: false
hadoop_heapsize: 512

# HBASE
hbase_conf_dir: /etc/hbase/conf
hbase_heapsize: 256

# Dependencies
maven_version: 3.3.9
idea_version: 14.0.3
# idea_dir_unpackaged is the name of the directory that comes out of the tarball
idea_dir_unpackaged: idea-IU-139.1117.1
idea_artifact: ideaIU-{{ idea_version }}.tar.gz
