---
# base.yml
#
# add dev user and configure base OS

- name: "install libselinux-python for ansible"
  yum:
    name: libselinux-python
    state: present
  become: yes


- name: install xauth for x11 forwarding
  yum:
    name: xauth
    state: present
  become: yes


# dev user
- name: add dev user
  user:
    name: "{{ dev_user }}"
  become: yes


- name: add class user to becomeers
  lineinfile:
    dest: /etc/sudoers
    line: "{{ dev_user }} ALL=(ALL) NOPASSWD: ALL"
  become: yes


- name: turn off swap
  sysctl:
    name: vm.swappiness
    value: 0
    ignoreerrors: yes
  become: yes


- name: increase native threads and open files
  template:
    src: templates/limits.conf.j2
    dest: /etc/security/limits.conf
  become: yes
