---
# development.yml
#
# install java and development tools

- name: install oracle jdk
  include: oracle-jdk.yml
  when: "{{ jdk_rpm is defined }}"


- name: install openjdk
  yum:
    name: java-1.8.0-openjdk
    state: present
  when: "{{ jdk_rpm is not defined }}"
  become: yes


# devtools
- name: create devtools dir
  file:
    path: "/home/{{ dev_user }}/devtools"
    state: directory


- name: create downloads dir
  file:
    path: "/home/{{ dev_user }}/downloads"
    state: directory


- name: install epel repo
  yum:
    name: epel-release
    state: present
  become: yes


- name: install basic software development packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - bash-completion
    - firefox
    - git
    - ruby
    - svn
    - unzip
    - vim-enhanced
  become: yes


- name: create personal bin
  file:
    path: "/home/{{ dev_user }}/bin"
    state: directory


# maven
- name: download maven
  get_url:
    url: "http://mirror.cc.columbia.edu/pub/software/apache/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "/home/{{ dev_user }}/downloads/apache-maven-{{ maven_version }}-bin.tar.gz"


- name: install maven
  unarchive: 
    src: "/home/{{ dev_user }}/downloads/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "/home/{{ dev_user }}/devtools"
    creates: "/home/{{ dev_user }}/devtools/apache-maven-{{ maven_version }}"
    copy: no


- name: symlink maven
  file: 
    path: "/home/{{ dev_user }}/devtools/maven"
    src: "/home/{{ dev_user }}/devtools/apache-maven-{{ maven_version }}"
    state: "link"


- name: set path in bashrc
  template:
    src: templates/bashrc
    dest: "/home/{{ dev_user }}/.bashrc"
