---
# hadoop-handlers.yml

- name: restart yarn
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - hadoop-yarn-nodemanager
    - hadoop-yarn-resourcemanager
  become: yes


- name: restart mapreduce
  service:
    name: hadoop-mapreduce-historyserver
    state: restarted
  become: yes


- name: restart hbase
  service:
    name: hbase-master
    state: restarted
  become: yes
