---
# provision.yml

- name: base OS configuration
  hosts: all
  tasks:
    - include: base.yml
      tags: base
    - include: development.yml
      tags: development
    - include: hadoop.yml
      tags: hadoop
    - include: pig.yml
      tags: pig
    - include: hbase.yml
      tags: hbase
  handlers:
    - include: hadoop-handlers.yml
